name: Flask CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r main/requirements.txt

      # 4️⃣ Run tests
      - name: Run pytest
        run: |
          pytest main/tests -v

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test   # only runs if tests pass

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t flask_lab_app ./main
